### ISSUE TITLE
Issue about using Magerun calling dev:template-hints

### ISSUE THREAD

**Issue by NeoHuy** [thanhvo-cse/dev-env#13]
I using Magerun to call dev:template-hints then showing this problem:
![Screen Shot 2020-02-24 at 9 01 12 PM](https://user-images.githubusercontent.com/2574360/75158500-d28ded80-5748-11ea-9a99-0cd977d0f7ab.png)

**Comment by thanhvo-cse** [comment]
This should be fixed on version 0.1.1.
Please update the package.
