### ISSUE TITLE
Need more details for configure's parameters

### ISSUE THREAD

**Issue by NeoHuy** [thanhvo-cse/dev-env#7]
When using dev-env configure --help need more info for all parameters.

**Comment by phnhan0301** [comment]
You can create sub-command in the form of configure: workspace by creating a file named workspace in the configure directory, oclif will scan and recognize it as sub-command

**For example**
```
| src
| -- commands
| ---- configure
| ------- workspace.ts
| ------- network.ts
| -------[more sub-command].ts
```

**Comment by NeoHuy** [comment]
I re-construct this command.
Please see it.
https://github.com/thanhvo-cse/dev-env/pull/12
